### PR TITLE
Removed MonoDevelop support as it's no longer part of premake-core

### PR DESCRIPTION
**Pull request by samsinsane**

### CODE REVIEW

**Comment by TurkeyMan** [comment]
I'm not sure why remove it... monodevelop must be an extension, and it should still be supported if the monodevelop extension is also present...
We had some discussion about this, when extensions have cross-extension dependency...

**Comment by samsinsane** [comment]
There's an open issue in core about why it's being removed, premake/premake-core#604. The code to extend monodevelop could technically stay, but the tests can't be run from core. Additionally, it seems odd to me for a module in core to extend a module that isn't in core, though to be fair, it does seem odd for the monodevelop module to have support for D.

**Comment by tvandijck** [comment]
I'm not against this change, although I have very little to say about either of these modules to be honest. It does however bring up an interesting usecase for cross-module dependencies. I wonder if there isn't a good way in the dlang plugin to say... we'll load these files when the monodev module is loaded, otherwise we don't..

I guess that would heavily depend on some kind of global variable beeing set by the monodev module, but that isn't an impossibility... We could enforce something like that in premake-core, and maybe already have..

**Comment by starkos** [comment]
Manu and I talked about this, and felt there was a need for something along the lines of `m = softRequire()` (a `require()` that returns `nil` if the module doesn't exist, rather than failing) or `moduleExists()`. We never settled on a name and it fell through the cracks.

**Comment by tvandijck** [comment]
"weakrequire", or "softrequire" work for me... sounds like a useful feature.

**Comment by samsinsane** [comment]
My main reason for removing all of it was to avoid shipping untested code in core. It seems a little weird to have a test suite and then ship code that we can't really test. Is this something we want to do though? I can revert the changes and just keep the changes to `_tests.lua` if you want?

**Comment by tvandijck** [comment]
I think if dlang is part of core, but monodev is not, then monodevelop needs to contains these pieces and inject it into premake-dlang with overrides when monodevelop gets loaded.

**Comment by TurkeyMan** [comment]
@tvandijck is right. That's the proper configuration.

**Comment by TurkeyMan** [comment]
Also, if MD is moving to MSBuild-proper, then it's all redundant (D and C/C++ output), and would be replaced by the VS generators, which are really actually MSBuild generators... assuming the MSBuild scripts MD uses are compatible with VS... but that's a parallel issue,

**Pull request merged**
